### ISSUE TITLE
sprite.image = '😁' doesn't work  in latest commit 

### ISSUE THREAD

**Issue by fangke-justcan** [quinton-ashley/p5play#332]
Hi , I am using p5play for my prototype and the emoji image is very useful. but the latest commit[3.22.15] seems to cause a problem. I get this error  when init a sprite's image with a emoji.  ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getImageData')
    at new EmojiImage (p5play.js:8368:18)
    at set image (p5play.js:1961:12)
    at setup (about:srcdoc:119:17)
    at g._setup (p5.min.js:2:465993)
    at g._start (p5.min.js:2:464676)
    at new g (p5.min.js:2:469060)
    at p5.min.js:2:454987

Thanks a lot for letting me know how i can fix the problem!

**Comment by quinton-ashley** [comment]
thanks for the report! just fixed in v3.22.16
